version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - risnet

  app:
    build: ./app
    depends_on:
      - db
    networks:
      - risnet
    volumes:
      - pgdata:/data

volumes:
  db_data:
  pgdata:

networks:
  risnet: